### PR TITLE
Improve overall wording

### PR DESCRIPTION
**Pull request by iddev5**
This PR makes changes to wording and structure.
No change in code is made. Even the comments in code are not modified so as to be decided separately in future.

### CODE REVIEW

**Comment by alichraghi** [comment]
thank you!

**Comment by iddev5** [comment]
@AliChraghi I just noticed that this PR had a weird side effect that the front page got dropped down to bottom because all other pages having numbers. I didn't not liked the approach the framework is doing for ordering. But maybe we need to change it back to being numbered? (if no other solution is found)

The reason behind removal of indexing from README.md page is that, its the home page and having it numbered might not look good. In another case, it can have the number index 0 to indicate that's its a special page.

**Comment by alichraghi** [comment]
I think if we change the name of the main page from `h1` to `h2` tag, it will be removed from the list, but it will always be displayed as the main page. or, as you said, put 0 behind it

**Comment by iddev5** [comment]
The first solution sounds okay to me!

**Comment by alichraghi** [comment]
@iddev5 does't work :(
i'll try your solution

**Pull request merged**
